## Behavior

keep-open=no
save-position-on-quit

## Screenshots

screenshot-format=png
screenshot-high-bit-depth=no
screenshot-png-compression=9
screenshot-directory="~/Imagens/MPV"
screenshot-template="%F-%p"
